CREATE DATABASE CIA_TECNICA

GO

USE CIA_TECNICA

GO

CREATE TABLE PESSOA_FISICA 
( 
PK_PESSOA_FISICA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CPF VARCHAR(14) NOT NULL,
DATA_NASCIMENTO DATETIME NOT NULL,
NOME VARCHAR(12) NOT NULL,
SOBRENOME VARCHAR (15) NOT NULL,
CEP VARCHAR(8) NOT NULL,
LOGRADOURO VARCHAR(100) NOT NULL,
NUMERO VARCHAR(6) NOT NULL,
COMPLEMENTO VARCHAR (30), 
BAIRRO VARCHAR (20) NOT NULL,
CIDADE VARCHAR (20) NOT NULL,
UF VARCHAR (2) NOT NULL
);

GO

CREATE TABLE PESSOA_JURIDICA
(
PK_PESSOA_JURIDICA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CNPJ VARCHAR(18) NOT NULL,
RAZAO_SOCIAL VARCHAR(50) NOT NULL,
NOME_FANTASIA VARCHAR(30) NOT NULL,
CEP VARCHAR(8) NOT NULL,
LOGRADOURO VARCHAR(100) NOT NULL,
NUMERO VARCHAR(6) NOT NULL,
COMPLEMENTO VARCHAR (30), 
BAIRRO VARCHAR (20) NOT NULL,
CIDADE VARCHAR (20) NOT NULL,
UF VARCHAR (2) NOT NULL
);

GO





